unstable_features = true

edition = "2024"

format_code_in_doc_comments = true
match_block_trailing_comma = true
imports_granularity = "Crate"
reorder_impl_items = true
use_field_init_shorthand = true
